### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ykweb** [simialbi/yii2-kanban#6]
Hello.
I have installed your wonderful module.
But I can't figure out the translation files. I did not find the i18n settings. Where can I place the files if I need a Russian translation?
Thank you

**Comment by simialbi** [comment]
Thank you 😄 
First of all, the fork https://github.com/mis-pulse/yii2-kanban is yours, isn't it?
You already placed the files on the correct location https://github.com/mis-pulse/yii2-kanban/blob/master/src/messages/ru/. I did not check if the compiled version (.mo file) got generated or copied from another language? If it's a copy, you need to compile it from .po with `msgfmt`. The alternative is to merge my changes since your fork, I already merged and compiled your russian translation. The module takes the correct language file automatically based on the configured application language if it exists. Otherwise it fallbaks to english.

**Comment by ykweb** [comment]
Copied your language file and it works, thanks.
I will finish the translation and inform you.
Have you planned on developing a Bootstrap 4 version?

**Comment by simialbi** [comment]
It is a bootstrap 4 version, isn't it?
