### ISSUE TITLE
No pagination for bucket tasks ?

### ISSUE THREAD

**Issue by i-internet** [simialbi/yii2-kanban#7]
First of all, thank you so much for such great work. 
My bucket contains 5000 plus tasks and it's getting slower every day.

**Comment by simialbi** [comment]
Hi @yii2backendwebdeveloper 
Thank you :smile:
Generally Kanban Boards are designed to have an overview over all running tasks and the possibility to manage them fast and simple. Because of this i'd like to prevent inserting a pagination. Having this amount of tasks in a single bucket is a bit special.

At the moment all tasks are rendered serverside while opening a board. A possible solution could be rendering them after opening a board via Ajax. But in your case this would mean 5000+ requests. I'm not sure if this is the better solution. Maybe some chunking (e.g. 500 per request) could solve this problem. I'll think about it.

**Comment by yii2backendwebdeveloper** [comment]
> Hi @yii2backendwebdeveloper
> Thank you 😄
> Generally Kanban Boards are designed to have an overview over all running tasks and the possibility to manage them fast and simple. Because of this i'd like to prevent inserting a pagination. Having this amount of tasks in a single bucket is a bit special.
> 
> At the moment all tasks are rendered serverside while opening a board. A possible solution could be rendering them after opening a board via Ajax. But in your case this would mean 5000+ requests. I'm not sure if this is the better solution. Maybe some chunking (e.g. 500 per request) could solve this problem. I'll think about it.

Thank you so much for replying. I have added a load more button to load data. BTW you are awsome

**Comment by simialbi** [comment]
I released a version 2 with `turbo` instead of pjax. It loads the buckets seperatly, so I'm not sure if a pagination is still needed
